#!/usr/bin/env bash
# script that installs and configure HAProxy on lb-01 server

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend local_server
    bind *:80
    mode http
    default_backend Web_Servers

backend Web_Servers
    balance roundrobin
    server web-01 35.174.205.207:80 check
    server web-02 54.174.195.151:80 check
EOT

# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
