#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# Requirement:
#	Format: IP HTTP_CODE
#	in a list format
#	You must use awk

awk '{print $1 " " $9}' apache-access.log
